### ISSUE TITLE
Failed to load the atom-playlist package : Cannot find module 'async'

### ISSUE THREAD

**Issue by dbqt** [Glavin001/atom-playlist#28]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Unknown Windows Version
**Thrown From**: [atom-playlist](https://github.com/dreid93/atom-playlist) package, v0.1.7

### Stack Trace

Failed to load the atom-playlist package

```
At Cannot find module 'async'

Error: Cannot find module 'async'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\dbqtran\AppData\Local\atom\app-0.204.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/dbqtran/.atom/packages/atom-playlist/lib/models/track_providers.coffee:11:11)
    at Object.<anonymous> (/C:/Users/dbqtran/.atom/packages/atom-playlist/lib/models/track_providers.coffee:56:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\dbqtran\AppData\Local\atom\app-0.204.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-playlist, v0.1.7
minimap, v4.9.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Not sure why. It has the dependency, `async`: https://github.com/Glavin001/atom-playlist/blob/master/package.json#L28

Try reinstalling.

**Comment by dbqt** [comment]
I just reinstalled, the same problem occured, also this:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Unknown Windows Version
**Thrown From**: [atom-playlist-master](https://github.com/dreid93/atom-playlist) package, v0.1.7


### Stack Trace

Failed to load the atom-playlist-master package

```
At '../bundle/components/fontawesome/less/font-awesome.less' wasn't found in C:\Users\dbqtran\.atom\packages\atom-playlist-master\stylesheets\fontawesome.less:1:0

LessError: '../bundle/components/fontawesome/less/font-awesome.less' wasn't found
  at C:\Users\dbqtran\.atom\packages\atom-playlist-master\stylesheets\fontawesome.less:1:0
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-playlist-master, v0.1.7

# Dev
No dev packages
```

Also, I am installing manually (decompressing the zip from github into the package folder of atom. I cannot install directly from atom nor with apm because of the network limitation where I work.
